Bypass logscale=True of matplotlib.pyplot
    - The logscale=True of matplotlib.pyplot does not work!
    - It throws an error:
      ValueError: Data has no positive values, and therefore can not be log-scaled.
    - It used to work before !
    - So, for now just pass the log of eke to pyplot